version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:fpm # 使用 PHP-FPM 镜像
    container_name: wordpress_app
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root_password
    volumes:
      - wordpress_data:/var/www/html
      - ./wp_plugins:/var/www/html/wp-content/plugins
    networks:
      - wordpress_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress_data:/var/www/html:ro
    ports:
      - "80:80"
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - wordpress_network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\qjsjy\workplace\wordpress-docker\data\db
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: C:\Users\qjsjy\workplace\wordpress-docker\data\wordpress
      o: bind

networks:
  wordpress_network:
